### ISSUE TITLE
Giving preference to completions by latex-autocomplete over autocomplete-plus

### ISSUE THREAD

**Issue by hasantahir** [Evpok/latex-autocomplete#17]
I understand the mess is due to autocomplete-plus. Is there a way to change the order the suggested completions complying with latex-autocomplete?

Here's an example:

![image](https://cloud.githubusercontent.com/assets/11236148/19605221/814925f8-977e-11e6-8498-9c798f52ca47.png)

Many thanks

**Comment by Evpok** [comment]
If you mean ”when completing labels and user macro”, then that is in the plan™ (it's mostly just adding a setting). But your screenshot seems to suggest something else, so would you mind expliciting what you want?

**Comment by hasantahir** [comment]
I want the latex reserved words to be given preference by the auto-complete-plus package. Is there a way that your package over-ride such rules? The screenshot illustrates my point. I would prefer a 'equation' suggested on top of 'equations'.

Thanks

**Comment by Evpok** [comment]
As of now, we don't provide autocompletion for LaTeX macros (except for reference ones) and environments. Without knowing your specific settings it is hard to know which provider is suggesting `equation` to you, but if I had to guess, I would say that it is autocomplete-plus SymbolProvider, which doesn't know that what `equation` means in a LaTeX context. Anyway, since this package is not the one making that suggestion (yet), I can't help you here, so I am closing this issue.

That said it would be great if we *did* support macro/environment completion, at least for such ubiquitous packages as `amsmath`, so if anyone wants to lend a hand for this **please do**!
