### ISSUE TITLE
Problem with repeated environment name

### ISSUE THREAD

**Issue by tim6her** [Evpok/latex-autocomplete#22]
I am using atom.io under macOS 10.12.6 and experiencing the weird behaviour of latex-autocomplete shown below. Unfortunately, I am new to  atom.io, so I could pinpoint where the problem arises.

Please, let me know if and how I can provide further data on this issue.

![latex-autocomplete](https://user-images.githubusercontent.com/11040405/30108700-981a9592-9303-11e7-8ab6-7011f8176808.gif)

**Comment by Evpok** [comment]
Yeah, I have noticed that, too. It is caused by the autocompletion of snippets from [language-latex](https://github.com/area/language-latex) and is not linked to latex-autocomplete (it even happens with latex-autocomplete disabled). It is the expected behaviour (`it` is completed to `\begin{itemize}\n\t\item \n\end{itemize}`) but I agree that it is annoying. Maybe you could report it [there](https://github.com/area/language-latex/issues).
